name: Bundle Update
description: A Buildkite plugin that runs bundle update
author: https://github.com/envato
requirements:
  - docker
configuration:
  properties:
    image:
      type: string
    pull-request:
      type: integer
      minimum: 1
    pull-request-metadata-key:
      type: string
    repository:
      type: string
    update:
      type: boolean
  oneOf:
    - required:
      - annotate
    - required:
      - update
  dependencies:
    image: [ update ]
    pull-request: [ annotate ]
    repository: [ annotate ]
