#!/bin/bash

set -euo pipefail

image=${BUILDKITE_PLUGIN_BUNDLE_UPDATE_IMAGE:-ruby}

echo
echo "--- :docker: Fetching the latest ${image} image"
echo

docker pull "${image}"

echo
echo "+++ :bundler: Running bundle update"
echo

args=(
  "--interactive"
  "--tty"
  "--rm"
  "--volume" "$PWD:/bundle_update"
  "--workdir" "/bundle_update"
)

docker run "${args[@]}" "${image}" bundle update --jobs=$(nproc)

if git diff-index --quiet HEAD -- Gemfile.lock; then
  echo
  echo "No updates"
else
  buildkite-agent meta-data set bundle-update-plugin-changes true
fi
